[package]
name = "kelpie"
version = "0.1.0"
edition = "2021"

[dependencies]
q_compress = "0.11.7"
sqlite = "0.36.0"
thiserror = "1.0.63"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
